All:
	gcc -o softmax_example.o softmax_example.c ../../random/ruspma_rand.c ../../array_sort/ruspma_array_sort.c ../../bandit/ruspma_softmax.c -lm
	gcc -o epsilon_example.o epsilon_example.c ../../random/ruspma_rand.c ../../array_sort/ruspma_array_sort.c ../../bandit/ruspma_epsilon_greedy.c -lm
